language: node_js
node_js:
  - stable

deploy:
  provider: heroku
  api_key:
    secure: CUnm2G8c0uz0C6CVjb5Gl7eJ6Z/Ur12kFpzmUDWm2UJlXQ6cfGR8icEQTLMMmL1cgOaTbOC2woHUjeJUSxRI0lj0dNd7aO2hQiXNDLfYygx+NtkKFISFdKGs6FLefFP69u6b4WDF2zM0P3aKQy8Gc8alxB9dHtgzmreSpDGfgi6k9Zk1ZJJWu/W2pk3qwEvNhwni4qxchWbfAZSmScvYudGdYspLWvXHJhHIMOwp19WsU8gZtSRHESNMxZVBedEOOc8y2dt4HKNAA+OcbKeejUShkJY26L9mbNz9pkmkUvQDE0qTtq9wEAQ/EsykCTI9ZV1xAP+0HY5pO4PSz5iO4kghwbFSyznZpHfeqRGAlJHdfGXbmFh1cGgfeXptwvNVLh1yRu3+1UA0Mizs+ZBXf9bf5jh8aFFp+qTJ5SLQDyjIpj2WAa7ZmpOtqAadxeXa4IsbBqwbsO8QWJveCNfrhHUgSr2MXcjVpMtMxNHV8JG8MksbiXJzYOl9pkTjoQk5mydP6sYtmrDJA/3PiE9i4mvKcAyCz0sUgND8uLH2B91pWTgUBcBZKLNayY9ytxorySJfV72758AJnlN7S9h4iuzlkE7LCk9p614jHD9gdb12aa3MPEJiKVzFs76NYLFo9p6xTktvcIbob8nNw/rXE+moCwB07RkYaRdGfyTblIs=
  app: oscar-stock-app
  on:
    repo: Maker-Mark/Stock-Portfolio-App
