language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  api_key:
    secure: s+C84c5DyTCIm6XvwJgXzpCupvvOYSd6g7YMG8Pd1a5beZXTTBwOPDnVq9JvH4qBLC8QkiqKOCvIEKFSXoJIittF89kKFPaBZ8GB33G6UsA+4j/bCvi4xf9E2WC0HGkd9DKSR+D+hfPFMkCh+oJgcxjhj6/8npobgMjz71hlduWhJS/+qPW462LUa3mZmYNqisszVHk/52oQ2VvVinYmEY41sC8r0PjDMro621ypC7sIdGIt8V6dF+R0K8smEsgZtDFaz5vjHszLJwExisOiCSq91HtyOxbqiK635cRkYg+ms+Ug0niQeTUfhkSS5Ja1ePaZi60DzqT9t2PsZrxeyphghmwdd5mTSYP+NuMYiGfVfOvDU9gJqXTZpM7tG7YkPCXEsv4zZ/meXweZZwLx2B2mznRDAJcwOuu9lLDfPgU5iM4Y4J5WQO2TxHV1R7EXobyVjDXeehcB+0RXJy1UCX8m38Jl9Uu28qP/0gqJXnFz+Z2TydqnjI0g6UaAJd4rZAo+9RWR5qan+SUfnamMba0T+djDVPm2mKErpTWPknyYvWGdzr2mDU0dcdT4xUd5GY9RgOcqE/3DWmQmwIetBoyS0IZJrU1eEeSy3RJGasfF7RM4vfea5aG9aLg/83mLPkMByIXPtpbZQIFGyFq7dVn6rrMfdsIqUznp5eOjX/A=
  app: oscar-stock-app
  on:
    repo: Maker-Mark/Stock-Portfolio-App
