language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: XwGXAhSnbRl3EzQ3YkrilQoSEffDc/Q2etn0liWhRRA+FmxB9vRfP3TTs6VTipnSQOuxqz0D47BZDGWSTCbD3N/fnmhzfNulDjJlyIE/tiyCWZRW+S5GN+cPnyn82xzEasN3xx5uw+uW7YRaffzWhsCSNbWmL78RAZCBxTsU1mAzQqhfIyrg8tdEYirBtsTdtiMwsJLwNaDn3xRXumbzQMcAV3S2czAOIZUg6DDkHkcFij9CN8QowydaC616hCQixpXPvgmqAStzbQVzjgDUfMfbaxYM8O8BPsMmOMFXvPgVw/J9c/P0yVzIwKz6AX9YwzRHloji82FtEhbY5wGwmxRnxrdi9rk0EUROo9fA/JyaZszh8Kuf6GE0FR09unmy8gb1N+ghS4tjaldPhtY+YDJXBPW1PkOihKndzgsVkGqtYzmwX+iL58uVZNJeKSkAqnrOuZcKR1N8qcy0CgHfKqpuShMsX5uopO+RXJw/a5tjjbf4Pn/TKe5hPy+i13MgDwXajeTT7utytN58AZT7Q83F6R7zEJFMWumQJZnCLGx3YkD9CN1UAjo0xHAbLquHa8NuroCFG2mOAglOwDPpwjBK+h1LaYqB6sXkmvgIpuqgA/civ0VwIFdkcux8S9mY4Wr/U4kcsj0ttaEuUVU2d6rS+yYQ5l0RZ8O2VqmAYnI=
  app: oscar-stock-api
  on:
    repo: Maker-Mark/Stock-Portfolio-App
